/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVendasBalcaoRouteImport } from './routes/_admin/vendas-balcao'
import { Route as AdminProdutosRouteImport } from './routes/_admin/produtos'
import { Route as AdminPedidosRouteImport } from './routes/_admin/pedidos'
import { Route as AdminEntradaProdutosRouteImport } from './routes/_admin/entrada-produtos'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminConfiguracoesRouteImport } from './routes/_admin/configuracoes'
import { Route as AdminClientesRouteImport } from './routes/_admin/clientes'
import { Route as AdminBalcaoRouteImport } from './routes/_admin/balcao'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendasBalcaoRoute = AdminVendasBalcaoRouteImport.update({
  id: '/vendas-balcao',
  path: '/vendas-balcao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntradaProdutosRoute = AdminEntradaProdutosRouteImport.update({
  id: '/entrada-produtos',
  path: '/entrada-produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBalcaoRoute = AdminBalcaoRouteImport.update({
  id: '/balcao',
  path: '/balcao',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/balcao': typeof AdminBalcaoRoute
  '/clientes': typeof AdminClientesRoute
  '/configuracoes': typeof AdminConfiguracoesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/entrada-produtos': typeof AdminEntradaProdutosRoute
  '/pedidos': typeof AdminPedidosRoute
  '/produtos': typeof AdminProdutosRoute
  '/vendas-balcao': typeof AdminVendasBalcaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/balcao': typeof AdminBalcaoRoute
  '/clientes': typeof AdminClientesRoute
  '/configuracoes': typeof AdminConfiguracoesRoute
  '/dashboard': typeof AdminDashboardRoute
  '/entrada-produtos': typeof AdminEntradaProdutosRoute
  '/pedidos': typeof AdminPedidosRoute
  '/produtos': typeof AdminProdutosRoute
  '/vendas-balcao': typeof AdminVendasBalcaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/_admin/balcao': typeof AdminBalcaoRoute
  '/_admin/clientes': typeof AdminClientesRoute
  '/_admin/configuracoes': typeof AdminConfiguracoesRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/entrada-produtos': typeof AdminEntradaProdutosRoute
  '/_admin/pedidos': typeof AdminPedidosRoute
  '/_admin/produtos': typeof AdminProdutosRoute
  '/_admin/vendas-balcao': typeof AdminVendasBalcaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/balcao'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/entrada-produtos'
    | '/pedidos'
    | '/produtos'
    | '/vendas-balcao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/balcao'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/entrada-produtos'
    | '/pedidos'
    | '/produtos'
    | '/vendas-balcao'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/cadastro'
    | '/login'
    | '/_admin/balcao'
    | '/_admin/clientes'
    | '/_admin/configuracoes'
    | '/_admin/dashboard'
    | '/_admin/entrada-produtos'
    | '/_admin/pedidos'
    | '/_admin/produtos'
    | '/_admin/vendas-balcao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/vendas-balcao': {
      id: '/_admin/vendas-balcao'
      path: '/vendas-balcao'
      fullPath: '/vendas-balcao'
      preLoaderRoute: typeof AdminVendasBalcaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/produtos': {
      id: '/_admin/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pedidos': {
      id: '/_admin/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/entrada-produtos': {
      id: '/_admin/entrada-produtos'
      path: '/entrada-produtos'
      fullPath: '/entrada-produtos'
      preLoaderRoute: typeof AdminEntradaProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/configuracoes': {
      id: '/_admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/clientes': {
      id: '/_admin/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/balcao': {
      id: '/_admin/balcao'
      path: '/balcao'
      fullPath: '/balcao'
      preLoaderRoute: typeof AdminBalcaoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBalcaoRoute: typeof AdminBalcaoRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEntradaProdutosRoute: typeof AdminEntradaProdutosRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminVendasBalcaoRoute: typeof AdminVendasBalcaoRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBalcaoRoute: AdminBalcaoRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEntradaProdutosRoute: AdminEntradaProdutosRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminVendasBalcaoRoute: AdminVendasBalcaoRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
